import type { QuizQuestion } from "./quizTypes";

/** 各難易度を30問にするための追加問題（id 31–90） */
export const moreQuestions: QuizQuestion[] = [
  // ========== 初心者 追加 (20) ==========
  {
    id: 31,
    difficulty: "beginner",
    title: "条件式の書き方",
    description:
      "準備完了かどうかを判定する処理です。条件の評価として誤っている行を1つ選んでください。",
    code: [
      "public class JobRunner {",
      "    private final TaskScheduler scheduler;",
      "",
      "    public JobRunner(TaskScheduler scheduler) {",
      "        this.scheduler = Objects.requireNonNull(scheduler);",
      "    }",
      "",
      "    public void startIfReady(boolean ready) {",
      "        logStatus(\"checking readiness\");",
      "        if (ready = true) {",
      "            run();",
      "        }",
      "    }",
      "",
      "    private void run() {",
      "        scheduler.execute();",
      "    }",
      "",
      "    private void logStatus(String msg) {",
      "        // logger.debug(msg);",
      "    }",
      "}",
    ],
    antiPatternLines: [10],
    patternName: "条件式での代入",
    explanation:
      "if (ready = true) は比較ではなく代入です。常に true になり、ready の値も書き換わります。比較には == や、単純に if (ready) を使いましょう。",
    hint: "この式は「比べて」いますか、それとも「入れています」か？",
  },
  {
    id: 32,
    difficulty: "beginner",
    title: "配列の比較",
    description:
      "2つの配列が同じ内容かを調べる処理です。意図どおりに動かないことがある行を1つ選んでください。",
    code: [
      "public final class ArrayComparer {",
      "    public boolean same(int[] a, int[] b) {",
      "        if (a == null || b == null) {",
      "            return a == b;",
      "        }",
      "        if (a.length != b.length) {",
      "            return false;",
      "        }",
      "        return a == b;",
      "    }",
      "",
      "    public int[] copy(int[] src) {",
      "        return Arrays.copyOf(src, src.length);",
      "    }",
      "}",
    ],
    antiPatternLines: [9],
    patternName: "配列の == 比較",
    explanation:
      "配列の == は参照の同一性だけを見ます。中身の比較には Arrays.equals(a, b) を使いましょう。",
    hint: "別インスタンスでも中身が同じことはありますか？",
  },
  {
    id: 33,
    difficulty: "beginner",
    title: "割り算",
    description:
      "平均値を計算する処理です。実行時例外を招きうる行を1つ選んでください。",
    code: [
      "public final class StatsCalculator {",
      "    private final Logger logger = LoggerFactory.getLogger(StatsCalculator.class);",
      "",
      "    public int average(int total, int count) {",
      "        if (total < 0) {",
      "            throw new IllegalArgumentException(\"total must be non-negative\");",
      "        }",
      "        logger.debug(\"average: total={}, count={}\", total, count);",
      "        return total / count;",
      "    }",
      "",
      "    public int sum(int[] values) {",
      "        int s = 0;",
      "        for (int v : values) {",
      "            s += v;",
      "        }",
      "        return s;",
      "    }",
      "}",
    ],
    antiPatternLines: [9],
    patternName: "ゼロ除算の未考慮",
    explanation:
      "count が 0 のとき ArithmeticException になります。除算前に count を検証するか、呼び出し側の契約を明確にしましょう。",
    hint: "分母が 0 だったらどうなりますか？",
  },
  {
    id: 34,
    difficulty: "beginner",
    title: "例外の見せ方",
    description:
      "失敗時の扱いです。運用やデバッグの観点で好ましくない行を1つ選んでください。",
    code: [
      "public class ConfigLoader {",
      "    private static final Logger logger = LoggerFactory.getLogger(ConfigLoader.class);",
      "    private final Path configPath;",
      "",
      "    public ConfigLoader(Path configPath) {",
      "        this.configPath = Objects.requireNonNull(configPath);",
      "    }",
      "",
      "    public void load() {",
      "        try {",
      "            doLoad();",
      "            logger.info(\"config loaded from {}\", configPath);",
      "        } catch (IOException e) {",
      "            e.printStackTrace();",
      "        }",
      "    }",
      "",
      "    private void doLoad() throws IOException {",
      "        Files.readString(configPath);",
      "    }",
      "}",
    ],
    antiPatternLines: [14],
    patternName: "printStackTrace への依存",
    explanation:
      "printStackTrace は標準エラーへ直接出し、ログレベルや出力先を制御できません。ロガー経由で記録するか、適切に再スローしましょう。",
    hint: "本番でスタックトレースの行き先は決まっていますか？",
  },
  {
    id: 35,
    difficulty: "beginner",
    title: "文字列リテラル",
    description:
      "ステータス判定です。可読性・保守性の観点で問題のある行を選んでください。",
    code: [
      "public class OrderStatusChecker {",
      "    private static final String STATUS_ACTIVE = \"ACTIVE\";",
      "",
      "    public boolean isActive(String status) {",
      "        if (status == null) return false;",
      "        return STATUS_ACTIVE.equals(status);",
      "    }",
      "",
      "    public boolean isDone(String status) {",
      "        return status.equals(\"DONE\");",
      "    }",
      "",
      "    public boolean isFailed(String status) {",
      "        return status.equals(\"FAILED\");",
      "    }",
      "",
      "    public String normalize(String status) {",
      "        return status == null ? \"\" : status.trim().toUpperCase();",
      "    }",
      "}",
    ],
    antiPatternLines: [10, 14],
    patternName: "マジックストリング",
    explanation:
      "\"DONE\" や \"FAILED\" がコードに直書きされています。定数や enum にすると、綴りミスや変更漏れを防げます（status が null のときは NPE も起きます）。",
    hint: "同じ意味の文字列が散らばっていませんか？",
  },
  {
    id: 36,
    difficulty: "beginner",
    title: "価格計算",
    description:
      "価格を計算して返すメソッドです。制御の流れとして不自然な行を1つ選んでください。",
    code: [
      "public class PriceCalculator {",
      "    private final TaxService taxService;",
      "",
      "    public PriceCalculator(TaxService taxService) {",
      "        this.taxService = Objects.requireNonNull(taxService);",
      "    }",
      "",
      "    public int calc(int x) {",
      "        if (x < 0) {",
      "            throw new IllegalArgumentException(\"x must be non-negative\");",
      "        }",
      "        return x * 2;",
      "        System.out.println(\"done\");",
      "    }",
      "",
      "    public int withTax(int x) {",
      "        return taxService.apply(calc(x));",
      "    }",
      "}",
    ],
    antiPatternLines: [13],
    patternName: "到達不能コード",
    explanation:
      "return の後の文は決して実行されません。不要なら削除し、必要な処理なら return の前に移しましょう。",
    hint: "この行はいつ実行されますか？",
  },
  {
    id: 37,
    difficulty: "beginner",
    title: "文字の取り出し",
    description:
      "先頭文字を返す処理です。実行時例外を招きうる行を1つ選んでください。",
    code: [
      "public class TextHelper {",
      "    public char firstChar(String text) {",
      "        if (text == null) {",
      "            throw new IllegalArgumentException(\"text is null\");",
      "        }",
      "        return text.charAt(0);",
      "    }",
      "",
      "    public boolean isBlank(String text) {",
      "        return text == null || text.isBlank();",
      "    }",
      "",
      "    public String trimOrEmpty(String text) {",
      "        return text == null ? \"\" : text.trim();",
      "    }",
      "}",
    ],
    antiPatternLines: [6],
    patternName: "空文字への無防備な charAt",
    explanation:
      "text が空文字だと StringIndexOutOfBoundsException になります。長さを確認してから取り出すか、isEmpty を先に見ましょう。",
    hint: "空の文字列でも 0 番目はありますか？",
  },
  {
    id: 38,
    difficulty: "beginner",
    title: "捕捉する例外の種類",
    description:
      "処理の失敗を捕まえるコードです。捕捉範囲として広すぎる行を1つ選んでください。",
    code: [
      "public class TaskRunner {",
      "    private static final Logger logger = LoggerFactory.getLogger(TaskRunner.class);",
      "    private final Task task;",
      "",
      "    public TaskRunner(Task task) {",
      "        this.task = Objects.requireNonNull(task);",
      "    }",
      "",
      "    public void runTask() {",
      "        try {",
      "            task.execute();",
      "            logger.info(\"task completed\");",
      "        } catch (Throwable t) {",
      "            logger.error(\"failed\", t);",
      "        }",
      "    }",
      "",
      "    public boolean isReady() {",
      "        return task != null;",
      "    }",
      "}",
    ],
    antiPatternLines: [13],
    patternName: "Throwable の捕捉",
    explanation:
      "Throwable は Error まで含むため、OutOfMemoryError など本来捕捉すべきでないものまで捕まえ得ます。必要な例外型に絞りましょう。",
    hint: "Error まで同じ扱いでよいですか？",
  },
  {
    id: 39,
    difficulty: "beginner",
    title: "プロセスの終了",
    description:
      "ライブラリ内のユーティリティです。呼び出し側に影響しすぎる行を1つ選んでください。",
    code: [
      "public final class StartupGuard {",
      "    private static final Logger logger = LoggerFactory.getLogger(StartupGuard.class);",
      "",
      "    public void ensureReady(boolean ready) {",
      "        if (!ready) {",
      "            logger.error(\"application not ready\");",
      "            System.exit(1);",
      "        }",
      "    }",
      "",
      "    public void ensureReadyOrThrow(boolean ready) {",
      "        if (!ready) {",
      "            throw new IllegalStateException(\"not ready\");",
      "        }",
      "    }",
      "}",
    ],
    antiPatternLines: [7],
    patternName: "System.exit の安易な使用",
    explanation:
      "System.exit は JVM 全体を終了させます。ライブラリや共有コンポーネントでは例外を投げるなど、呼び出し側に判断を委ねる方が安全です。",
    hint: "このメソッドはアプリ全体を止めますか？",
  },
  {
    id: 40,
    difficulty: "beginner",
    title: "秘密情報の置き場所",
    description:
      "外部サービス接続の設定です。セキュリティ上問題のある行を1つ選んでください。",
    code: [
      "public class MailClient {",
      "    private static final String PASSWORD = \"s3cret!\";",
      "    private static final String USERNAME = \"admin\";",
      "    private final SmtpServer server;",
      "",
      "    public MailClient(SmtpServer server) {",
      "        this.server = Objects.requireNonNull(server);",
      "    }",
      "",
      "    public void connect() {",
      "        login(USERNAME, PASSWORD);",
      "        server.handshake();",
      "    }",
      "",
      "    private void login(String user, String pass) {",
      "        server.authenticate(user, pass);",
      "    }",
      "}",
    ],
    antiPatternLines: [2],
    patternName: "ソースコードへの秘密情報の埋め込み",
    explanation:
      "パスワードをソースに直書きすると、リポジトリ漏洩時に危険です。環境変数やシークレット管理を使いましょう。",
    hint: "この文字列はリポジトリに入りませんか？",
  },
  {
    id: 41,
    difficulty: "beginner",
    title: "型の変換",
    description:
      "文字列を数値にする処理です。実行時例外を招きうる行を1つ選んでください。",
    code: [
      "public class NumberParser {",
      "    private final Logger logger = LoggerFactory.getLogger(NumberParser.class);",
      "",
      "    public int parse(String raw) {",
      "        if (raw == null) {",
      "            throw new IllegalArgumentException(\"raw is null\");",
      "        }",
      "        String trimmed = raw.trim();",
      "        logger.debug(\"parsing: {}\", trimmed);",
      "        return Integer.parseInt(raw);",
      "    }",
      "",
      "    public boolean isNumeric(String raw) {",
      "        if (raw == null || raw.isBlank()) return false;",
      "        return raw.chars().allMatch(Character::isDigit);",
      "    }",
      "}",
    ],
    antiPatternLines: [10],
    patternName: "入力検証なしの parseInt",
    explanation:
      "不正な文字列だと NumberFormatException になります。形式チェックや例外処理、Optional 的な戻り値設計を検討しましょう。",
    hint: "数字以外が入ってきたら？",
  },
  {
    id: 42,
    difficulty: "beginner",
    title: "ループの終了条件",
    description:
      "リストを走査する処理です。実行時例外を招きうる行を1つ選んでください。",
    code: [
      "public class ItemPrinter {",
      "    private final Logger logger = LoggerFactory.getLogger(ItemPrinter.class);",
      "",
      "    public void printAll(List<String> items) {",
      "        if (items == null || items.isEmpty()) {",
      "            logger.info(\"no items to print\");",
      "            return;",
      "        }",
      "        for (int i = 0; i <= items.size(); i++) {",
      "            System.out.println(items.get(i));",
      "        }",
      "    }",
      "",
      "    public int count(List<String> items) {",
      "        return items == null ? 0 : items.size();",
      "    }",
      "}",
    ],
    antiPatternLines: [9],
    patternName: "off-by-one（境界条件の誤り）",
    explanation:
      "i <= size() だと最後に size() 番目へアクセスし IndexOutOfBoundsException になります。通常は i < size() です。",
    hint: "最後の有効な添字はいくつですか？",
  },
  {
    id: 43,
    difficulty: "beginner",
    title: "真偽値の返し方",
    description:
      "数値の性質を判定するメソッドです。簡潔に書けるのに冗長になっている行を選んでください。",
    code: [
      "public class NumberRules {",
      "    public boolean isPositive(int n) {",
      "        if (n > 0) {",
      "            return true;",
      "        } else {",
      "            return false;",
      "        }",
      "    }",
      "",
      "    public int abs(int n) {",
      "        return n < 0 ? -n : n;",
      "    }",
      "",
      "    public int signum(int n) {",
      "        if (n > 0) return 1;",
      "        if (n < 0) return -1;",
      "        return 0;",
      "    }",
      "}",
    ],
    antiPatternLines: [3, 4, 5, 6],
    patternName: "不要な if-else による boolean 返却",
    explanation:
      "return n > 0; と書けば十分です。true/false を分岐で返すと読みにくく、ミスの温床になります。",
    hint: "条件式そのものを返せませんか？",
  },
  {
    id: 44,
    difficulty: "beginner",
    title: "挨拶メッセージ",
    description:
      "名前を受け取り挨拶文を返す処理です。文字列の扱いとして無駄がある行を1つ選んでください。",
    code: [
      "public class GreetingService {",
      "",
      "  public String message(String name) {",
      "    if (name == null || name.isBlank()) {",
      "      throw new IllegalArgumentException(\"name is required\");",
      "    }",
      "    StringBuilder sb = new StringBuilder(new String(\"Hello, \"));",
      "    sb.append(name);",
      "    return sb.toString();",
      "  }",
      "",
      "  public String shortName(String name) {",
      "    return name == null ? \"\" : name.strip();",
      "  }",
      "}",
    ],
    antiPatternLines: [7],
    patternName: "不要な new String",
    explanation:
      "new String(\"Hello, \") は余分なコピーを作ります。文字列リテラルをそのまま渡せば十分です。",
    hint: "リテラルをわざわざ包む必要はありますか？",
  },
  {
    id: 45,
    difficulty: "beginner",
    title: "クラス設計の基本",
    description:
      "座標を表すクラスです。不変であるべき値が書き換え可能な行を選んでください。",
    code: [
      "public class Point {",
      "    public int x;",
      "    public int y;",
      "",
      "    public Point(int x, int y) {",
      "        this.x = x;",
      "        this.y = y;",
      "    }",
      "",
      "    public double distanceFromOrigin() {",
      "        return Math.sqrt(x * x + y * y);",
      "    }",
      "",
      "    public String toLabel() {",
      "        return \"(\" + x + \", \" + y + \")\";",
      "    }",
      "}",
    ],
    antiPatternLines: [2, 3],
    patternName: "可変な public フィールド",
    explanation:
      "座標が外から自由に変わると、不変条件を保てません。private final にしてコンストラクタでセットしましょう。",
    hint: "生成後も自由に書き換えられますか？",
  },
  {
    id: 46,
    difficulty: "beginner",
    title: "メソッドの引数",
    description:
      "ユーザー登録処理です。不正な入力を許してしまう行を1つ選んでください。",
    code: [
      "public class UserRegistration {",
      "    private String email;",
      "    private final UserRepository repository;",
      "",
      "    public UserRegistration(UserRepository repository) {",
      "        this.repository = Objects.requireNonNull(repository);",
      "    }",
      "",
      "    public void register(String email) {",
      "        this.email = email;",
      "        save();",
      "    }",
      "",
      "    private void save() {",
      "        repository.save(new User(email));",
      "    }",
      "",
      "    public String getEmail() {",
      "        return email;",
      "    }",
      "}",
    ],
    antiPatternLines: [10],
    patternName: "引数の未検証",
    explanation:
      "null や空文字のまま保存すると、後続で NPE や不正データになります。受け取り時に検証しましょう。",
    hint: "email が null でもそのまま通りますか？",
  },
  {
    id: 47,
    difficulty: "beginner",
    title: "リストの初期化",
    description:
      "固定の選択肢を返す処理です。後から内容が変わってしまう行を1つ選んでください。",
    code: [
      "public class SurveyOptions {",
      "    private static final Logger logger = LoggerFactory.getLogger(SurveyOptions.class);",
      "",
      "    public List<String> options() {",
      "        return Arrays.asList(\"A\", \"B\", \"C\");",
      "    }",
      "",
      "    public void logOptions() {",
      "        List<String> opts = options();",
      "        logger.info(\"options: {}\", opts);",
      "    }",
      "",
      "    public int optionCount() {",
      "        return options().size();",
      "    }",
      "}",
    ],
    antiPatternLines: [5],
    patternName: "固定長リストの誤解（set 可能な asList）",
    explanation:
      "Arrays.asList は要素の set が可能で、呼び出し側が書き換えられます。不変が必要なら List.of や unmodifiableList を検討しましょう。",
    hint: "返したリストは本当に変更できませんか？",
  },
  {
    id: 48,
    difficulty: "beginner",
    title: "日付の文字列化",
    description:
      "今日の日付を文字列にする処理です。環境依存になりやすい行を1つ選んでください。",
    code: [
      "public class DateFormatter {",
      "    private final Clock clock;",
      "",
      "    public DateFormatter(Clock clock) {",
      "        this.clock = Objects.requireNonNull(clock);",
      "    }",
      "",
      "    public String today() {",
      "        return Date.from(clock.instant()).toString();",
      "    }",
      "",
      "    public Instant now() {",
      "        return clock.instant();",
      "    }",
      "}",
    ],
    antiPatternLines: [9],
    patternName: "Date#toString への依存",
    explanation:
      "Date#toString の形式はロケールや実装に依存し、パースにも向きません。DateTimeFormatter などで明示的に整形しましょう。",
    hint: "この文字列の形式は仕様として安定していますか？",
  },
  {
    id: 49,
    difficulty: "beginner",
    title: "カウンタの更新",
    description:
      "アクセス数を数える処理です。意図しない結果になりうる行を1つ選んでください。",
    code: [
      "public class AccessCounter {",
      "    private int count;",
      "",
      "    public void hit() {",
      "        count = count++;",
      "    }",
      "",
      "    public int getCount() {",
      "        return count;",
      "    }",
      "",
      "    public void reset() {",
      "        count = 0;",
      "    }",
      "}",
    ],
    antiPatternLines: [5],
    patternName: "count = count++ の誤用",
    explanation:
      "count++ は古い値を返し、その後インクリメントします。count = count++ だと結果的に増えません。count++ または count += 1 と書きましょう。",
    hint: "代入の右辺が返す値は、増える前ですか後ですか？",
  },
  {
    id: 50,
    difficulty: "beginner",
    title: "finally の使い方",
    description:
      "結果を返す処理です。例外の情報を打ち消してしまう行を1つ選んでください。",
    code: [
      "public class DataReader {",
      "    private final Path dataPath;",
      "",
      "    public DataReader(Path dataPath) {",
      "        this.dataPath = Objects.requireNonNull(dataPath);",
      "    }",
      "",
      "    public int read() {",
      "        try {",
      "            return doRead();",
      "        } finally {",
      "            return 0;",
      "        }",
      "    }",
      "",
      "    private int doRead() throws IOException {",
      "        return Integer.parseInt(Files.readString(dataPath).trim());",
      "    }",
      "}",
    ],
    antiPatternLines: [12],
    patternName: "finally での return",
    explanation:
      "finally で return すると、try で起きた例外や本来の戻り値が握りつぶされます。finally ではリソース解放などに留めましょう。",
    hint: "例外が起きても、最終的に何が返りますか？",
  },

  // ========== 中級者 追加 (20) ==========
  {
    id: 51,
    difficulty: "intermediate",
    title: "防御的コピー",
    description:
      "期間を表すクラスです。外部から内部状態を変えられてしまう行を選んでください。",
    code: [
      "public class Period {",
      "    private final Date start;",
      "    private final String label;",
      "",
      "    public Period(Date start, String label) {",
      "        this.start = start;",
      "        this.label = Objects.requireNonNull(label);",
      "    }",
      "",
      "    public Date getStart() {",
      "        return start;",
      "    }",
      "",
      "    public String getLabel() {",
      "        return label;",
      "    }",
      "",
      "    public boolean isBefore(Date other) {",
      "        return start.before(other);",
      "    }",
      "}",
    ],
    antiPatternLines: [6, 10],
    patternName: "可変オブジェクトの取り込み・露出",
    explanation:
      "Date は可変です。受け取った参照や返した参照経由で中身を変えられます。コンストラクタと getter で防御的コピーをしましょう。",
    hint: "返した Date の setTime は誰でも呼べますか？",
  },
  {
    id: 52,
    difficulty: "intermediate",
    title: "ログメッセージの組み立て",
    description:
      "デバッグログを出す処理です。性能上好ましくない行を1つ選んでください。",
    code: [
      "public class UserLogger {",
      "    private static final Logger logger = LoggerFactory.getLogger(UserLogger.class);",
      "",
      "    public void debugUser(User user) {",
      "        if (user == null) return;",
      "        logger.debug(\"user=\" + user.toDetailString());",
      "    }",
      "",
      "    public String label(User user) {",
      "        return user == null ? \"anonymous\" : user.getId();",
      "    }",
      "}",
    ],
    antiPatternLines: [6],
    patternName: "ログレベル判定前のメッセージ構築",
    explanation:
      "debug が無効でも toDetailString と文字列連結が走ります。logger.isDebugEnabled() やパラメータ付きログ（\"user={}\", user）を使いましょう。",
    hint: "ログレベルが OFF でも、この計算は走りますか？",
  },
  {
    id: 53,
    difficulty: "intermediate",
    title: "ハッシュの一貫性",
    description:
      "値オブジェクトです。HashMap などで正しく動かなくなる実装行を1つ選んでください。",
    code: [
      "public class Sku {",
      "    private final String code;",
      "",
      "    public Sku(String code) {",
      "        this.code = Objects.requireNonNull(code);",
      "    }",
      "",
      "    public String getCode() {",
      "        return code;",
      "    }",
      "",
      "    @Override",
      "    public boolean equals(Object o) {",
      "        return o instanceof Sku s && code.equals(s.code);",
      "    }",
      "",
      "    @Override",
      "    public int hashCode() {",
      "        return 1;",
      "    }",
      "}",
    ],
    antiPatternLines: [19],
    patternName: "equals と矛盾する hashCode",
    explanation:
      "常に 1 を返す hashCode は等価なオブジェクトを同じバケツに押し込み、性能を壊します。またフィールドを使わない実装は保守時に equals とズレやすいです。Objects.hash(code) を使いましょう。",
    hint: "等しいオブジェクトのハッシュは同じである必要がありますが、中身を反映していますか？",
  },
  {
    id: 54,
    difficulty: "intermediate",
    title: "合計の計算",
    description:
      "合計を求める処理です。実行時例外を招きうる行を1つ選んでください。",
    code: [
      "public class SumCalculator {",
      "    public int sum(List<Integer> values) {",
      "        if (values == null || values.isEmpty()) {",
      "            return 0;",
      "        }",
      "        int total = 0;",
      "        for (Integer v : values) {",
      "            total += v;",
      "        }",
      "        return total;",
      "    }",
      "",
      "    public int count(List<?> values) {",
      "        return values == null ? 0 : values.size();",
      "    }",
      "}",
    ],
    antiPatternLines: [8],
    patternName: "null のアンボクシング",
    explanation:
      "List に null が含まれると、total += v で NullPointerException になります。null チェックや Objects.requireNonNullElse を検討しましょう。",
    hint: "v が null のとき加算はどうなりますか？",
  },
  {
    id: 55,
    difficulty: "intermediate",
    title: "ファイルの読み方",
    description:
      "テキストを読む処理です。文字化けや環境依存を招きうる行を1つ選んでください。",
    code: [
      "public class TextFileReader {",
      "    private final Logger logger = LoggerFactory.getLogger(TextFileReader.class);",
      "",
      "    public String read(Path path) throws IOException {",
      "        Objects.requireNonNull(path);",
      "        byte[] bytes = Files.readAllBytes(path);",
      "        logger.debug(\"read {} bytes from {}\", bytes.length, path);",
      "        return new String(bytes);",
      "    }",
      "",
      "    public long size(Path path) throws IOException {",
      "        return Files.size(path);",
      "    }",
      "}",
    ],
    antiPatternLines: [8],
    patternName: "デフォルト文字セットへの依存",
    explanation:
      "引数なしの new String(byte[]) はプラットフォームのデフォルト文字セットを使います。StandardCharsets.UTF_8 などを明示しましょう。",
    hint: "別 OS でも同じ文字に読めますか？",
  },
  {
    id: 56,
    difficulty: "intermediate",
    title: "クローン",
    description:
      "配列を複製する処理です。意図と違う共有が起きる行を1つ選んでください。",
    code: [
      "public class ArrayCopier {",
      "    public String[] copy(String[] source) {",
      "        if (source == null) {",
      "            return new String[0];",
      "        }",
      "        return source;",
      "    }",
      "",
      "    public int length(String[] source) {",
      "        return source == null ? 0 : source.length;",
      "    }",
      "",
      "    public boolean isEmpty(String[] source) {",
      "        return source == null || source.length == 0;",
      "    }",
      "}",
    ],
    antiPatternLines: [6],
    patternName: "参照の返しによる偽のコピー",
    explanation:
      "参照をそのまま返すと呼び出し側と配列を共有します。Arrays.copyOf や clone で実体を複製しましょう。",
    hint: "返した配列を書き換えると、元はどうなりますか？",
  },
  {
    id: 57,
    difficulty: "intermediate",
    title: "ユーザー取得",
    description:
      "ユーザー取得です。戻り値の設計として好ましくない行を1つ選んでください。",
    code: [
      "public class UserService {",
      "    private final UserRepository repository;",
      "",
      "    public UserService(UserRepository repository) {",
      "        this.repository = Objects.requireNonNull(repository);",
      "    }",
      "",
      "    public User getUser(long id) {",
      "        return repository.find(id).orElse(null);",
      "    }",
      "",
      "    public long repositoryId() {",
      "        return System.identityHashCode(repository);",
      "    }",
      "}",
    ],
    antiPatternLines: [9],
    patternName: "Optional から null を取り出す",
    explanation:
      "Optional を使う意味が薄れ、再び NPE のリスクが戻ります。Optional を返すか、orElseThrow / デフォルトオブジェクトを使いましょう。",
    hint: "見つからないときの戻り方は、呼び出し側にどんな負担をかけますか？",
  },
  {
    id: 58,
    difficulty: "intermediate",
    title: "名前の出力",
    description:
      "条件に合う名前を出力する処理です。実行時例外を招きうる行を1つ選んでください。",
    code: [
      "public class NamePrinter {",
      "    private static final Logger logger = LoggerFactory.getLogger(NamePrinter.class);",
      "",
      "    public void printLongNames(List<String> names) {",
      "        if (names == null) return;",
      "        Stream<String> stream = names.stream().filter(n -> n.length() > 3);",
      "        stream.forEach(System.out::println);",
      "        stream.count();",
      "    }",
      "",
      "    public boolean anyLongName(List<String> names) {",
      "        return names.stream().anyMatch(n -> n.length() > 3);",
      "    }",
      "}",
    ],
    antiPatternLines: [8],
    patternName: "消費済み Stream の再利用",
    explanation:
      "Stream は終端操作のあと再利用できません。count() で IllegalStateException になります。必要なら元データから作り直しましょう。",
    hint: "終端操作のあと同じ参照は、もう一度使えますか？",
  },
  {
    id: 59,
    difficulty: "intermediate",
    title: "可変引数と配列",
    description:
      "ログ出力のヘルパーです。ヒープ汚染や型安全性を損なう行を選んでください。",
    code: [
      "public class LogHelper {",
      "    private static final Logger logger = LoggerFactory.getLogger(LogHelper.class);",
      "",
      "    public void logAll(List<String>... groups) {",
      "        if (groups.length == 0) return;",
      "        Object[] rows = groups;",
      "        rows[0] = List.of(42);",
      "        String first = groups[0].get(0);",
      "        logger.info(\"first entry: {}\", first);",
      "    }",
      "",
      "    public void logSingle(List<String> group) {",
      "        if (group != null) logger.info(\"group: {}\", group);",
      "    }",
      "}",
    ],
    antiPatternLines: [6, 7],
    patternName: "ジェネリック可変引数のヒープ汚染",
    explanation:
      "ジェネリック可変引数は配列として扱われ、ヒープ汚染の温床です。Object[] 経由の代入は特に危険です。List の List を渡す設計にしましょう。",
    hint: "可変引数の実体は何の配列ですか？",
  },
  {
    id: 60,
    difficulty: "intermediate",
    title: "定数の定義",
    description:
      "設定クラスです。変更できてしまう定数宣言を選んでください。",
    code: [
      "public class Limits {",
      "    public static final int[] MAX = { 10, 20, 30 };",
      "    public static final String APP_NAME = \"JavaQuiz\";",
      "",
      "    public static int getMax(int index) {",
      "        return MAX[index];",
      "    }",
      "",
      "    public static String appName() {",
      "        return APP_NAME;",
      "    }",
      "}",
    ],
    antiPatternLines: [2],
    patternName: "final でも中身が可変な配列",
    explanation:
      "配列参照が final でも要素は書き換えられます。不変が必要なら List.of や防御的コピー、専用の不変オブジェクトを使いましょう。",
    hint: "MAX[0] = 99 はコンパイルできますか？",
  },
  {
    id: 61,
    difficulty: "intermediate",
    title: "例外の翻訳",
    description:
      "下位の例外を包む処理です。原因情報が失われる行を1つ選んでください。",
    code: [
      "public class EntitySaver {",
      "    private static final Logger logger = LoggerFactory.getLogger(EntitySaver.class);",
      "    private final EntityRepository repository;",
      "",
      "    public EntitySaver(EntityRepository repository) {",
      "        this.repository = Objects.requireNonNull(repository);",
      "    }",
      "",
      "    public void save(Entity e) {",
      "        Objects.requireNonNull(e);",
      "        try {",
      "            repository.insert(e);",
      "            logger.info(\"saved entity {}\", e.getId());",
      "        } catch (SQLException ex) {",
      "            throw new IllegalStateException(\"save failed\");",
      "        }",
      "    }",
      "}",
    ],
    antiPatternLines: [15],
    patternName: "原因例外の欠落",
    explanation:
      "cause を渡さないと元の SQLException が消えます。new IllegalStateException(\"save failed\", ex) のように原因をチェーンしましょう。",
    hint: "元の例外はどこに残りますか？",
  },
  {
    id: 62,
    difficulty: "intermediate",
    title: "比較の契約",
    description:
      "ソート用の比較です。契約違反になりうる行を1つ選んでください。",
    code: [
      "public class PlayerComparator {",
      "    public int compare(Player a, Player b) {",
      "        Objects.requireNonNull(a);",
      "        Objects.requireNonNull(b);",
      "        return a.score > b.score ? 1 : -1;",
      "    }",
      "",
      "    public List<Player> sort(List<Player> players) {",
      "        return players.stream().sorted(this::compare).toList();",
      "    }",
      "",
      "    public Player top(List<Player> players) {",
      "        return sort(players).get(0);",
      "    }",
      "}",
    ],
    antiPatternLines: [5],
    patternName: "compare で等価を返さない",
    explanation:
      "スコアが等しいときも -1 になり、compare(a,a)==0 や対称性が壊れます。等しい場合は 0 を返しましょう（Integer.compare など）。",
    hint: "同じスコアのとき何が返りますか？",
  },
  {
    id: 63,
    difficulty: "intermediate",
    title: "シングルトンの初期化",
    description:
      "設定の遅延ロードです。複数スレッドで壊れる行を選んでください。",
    code: [
      "public class Config {",
      "    private static Config instance;",
      "    private final Properties props = new Properties();",
      "",
      "    private Config() {",
      "        props.setProperty(\"env\", \"prod\");",
      "    }",
      "",
      "    public static Config get() {",
      "        if (instance == null) {",
      "            instance = new Config();",
      "        }",
      "        return instance;",
      "    }",
      "",
      "    public String get(String key) {",
      "        return props.getProperty(key);",
      "    }",
      "}",
    ],
    antiPatternLines: [10, 11],
    patternName: "同期なしの遅延初期化",
    explanation:
      "null チェックと生成がアトミックでないため、複数インスタンスが生まれ得ます。enum シングルトンやホルダークラス、同期を検討しましょう。",
    hint: "2スレッドが同時に null を見たら？",
  },
  {
    id: 64,
    difficulty: "intermediate",
    title: "API の戻り値",
    description:
      "検索 API です。エラーと空結果の区別がつかない行を1つ選んでください。",
    code: [
      "public class ItemSearchApi {",
      "    private static final Logger logger = LoggerFactory.getLogger(ItemSearchApi.class);",
      "    private final SearchClient client;",
      "",
      "    public ItemSearchApi(SearchClient client) {",
      "        this.client = Objects.requireNonNull(client);",
      "    }",
      "",
      "    public List<Item> search(String q) {",
      "        if (q == null || q.isBlank()) return List.of();",
      "        try {",
      "            return client.query(q);",
      "        } catch (IOException e) {",
      "            return List.of();",
      "        }",
      "    }",
      "}",
    ],
    antiPatternLines: [14],
    patternName: "失敗を空リストで隠す",
    explanation:
      "通信失敗も「0件」に見えるため、呼び出し側が誤った判断をします。例外を伝播するか、結果型で失敗を表現しましょう。",
    hint: "本当にヒットゼロなのか、失敗なのか？",
  },
  {
    id: 65,
    difficulty: "intermediate",
    title: "時間の扱い",
    description:
      "期限切れ判定です。テストや夏時間で困りやすい行を1つ選んでください。",
    code: [
      "public class SessionExpiry {",
      "    private static final long ONE_DAY_MS = 86_400_000L;",
      "",
      "    public boolean expired(long createdMillis) {",
      "        if (createdMillis < 0) {",
      "            throw new IllegalArgumentException(\"invalid timestamp\");",
      "        }",
      "        return System.currentTimeMillis() - createdMillis > 86_400_000;",
      "    }",
      "",
      "    public long ageMillis(long createdMillis) {",
      "        return System.currentTimeMillis() - createdMillis;",
      "    }",
      "}",
    ],
    antiPatternLines: [8],
    patternName: "マジックなミリ秒と現在時刻への直依存",
    explanation:
      "86400000 の意味が読み取りにくく、現在時刻に直依存するとテストが困難です。Duration や Clock を注入しましょう。",
    hint: "1日のミリ秒だと、読んだ人はすぐ分かりますか？",
  },
  {
    id: 66,
    difficulty: "intermediate",
    title: "リストのランダムアクセス",
    description:
      "真ん中の要素を頻繁に読む処理です。データ構造の選択としてまずい行を1つ選んでください。",
    code: [
      "public class ListMiddle {",
      "    public String middle(LinkedList<String> items) {",
      "        if (items == null || items.isEmpty()) {",
      "            throw new IllegalArgumentException(\"items is empty\");",
      "        }",
      "        return items.get(items.size() / 2);",
      "    }",
      "",
      "    public String first(LinkedList<String> items) {",
      "        return items.getFirst();",
      "    }",
      "",
      "    public int size(LinkedList<String> items) {",
      "        return items.size();",
      "    }",
      "}",
    ],
    antiPatternLines: [6],
    patternName: "LinkedList へのインデックスアクセス",
    explanation:
      "LinkedList の get(i) は先頭から辿るため O(n) です。ランダムアクセスが多いなら ArrayList を検討しましょう。",
    hint: "この get は何回のリンク辿りが必要ですか？",
  },
  {
    id: 67,
    difficulty: "intermediate",
    title: "入力ストリーム",
    description:
      "リクエストボディを読む処理です。リソースリークにつながる行を選んでください。",
    code: [
      "public class RequestBodyReader {",
      "    private final Logger logger = LoggerFactory.getLogger(RequestBodyReader.class);",
      "",
      "    public String body(InputStream in) throws IOException {",
      "        Objects.requireNonNull(in);",
      "        BufferedReader reader = new BufferedReader(new InputStreamReader(in));",
      "        String line = reader.readLine();",
      "        logger.debug(\"read {} chars\", line == null ? 0 : line.length());",
      "        return line;",
      "    }",
      "",
      "    public boolean hasContent(InputStream in) throws IOException {",
      "        return in.available() > 0;",
      "    }",
      "}",
    ],
    antiPatternLines: [6],
    patternName: "Reader の未クローズ",
    explanation:
      "Reader を閉じないと、元のストリームも適切に解放されないことがあります。try-with-resources を使いましょう。",
    hint: "開いた Reader は誰が閉じますか？",
  },
  {
    id: 68,
    difficulty: "intermediate",
    title: "金額の変換",
    description:
      "金額計算の入力です。精度が崩れる行を1つ選んでください。",
    code: [
      "public class MoneyConverter {",
      "    private static final int SCALE = 2;",
      "",
      "    public BigDecimal amount(double raw) {",
      "        if (Double.isNaN(raw) || Double.isInfinite(raw)) {",
      "            throw new IllegalArgumentException(\"invalid amount\");",
      "        }",
      "        return new BigDecimal(raw);",
      "    }",
      "",
      "    public int scale() {",
      "        return SCALE;",
      "    }",
      "}",
    ],
    antiPatternLines: [8],
    patternName: "double からの BigDecimal 生成",
    explanation:
      "new BigDecimal(0.1) は二進誤差をそのまま持ち込みます。new BigDecimal(\"0.1\") や valueOf を検討しましょう。",
    hint: "0.1 は double で正確に表せますか？",
  },
  {
    id: 69,
    difficulty: "intermediate",
    title: "非同期実行",
    description:
      "別スレッドでタスクを走らせたい処理です。意図した並行実行にならない行を1つ選んでください。",
    code: [
      "public class AsyncRunner {",
      "    private static final Logger logger = LoggerFactory.getLogger(AsyncRunner.class);",
      "",
      "    public void runAsync(Runnable task) {",
      "        Objects.requireNonNull(task);",
      "        Thread worker = new Thread(task);",
      "        worker.setName(\"async-worker\");",
      "        worker.run();",
      "    }",
      "",
      "    public String workerName() {",
      "        return \"async-worker\";",
      "    }",
      "}",
    ],
    antiPatternLines: [8],
    patternName: "Thread#run の直接呼び出し",
    explanation:
      "run() は現在のスレッドで同期実行します。新しいスレッドで動かすには start() を呼びます。",
    hint: "別スレッドはいつ始まりますか？",
  },
  {
    id: 70,
    difficulty: "intermediate",
    title: "キャッシュのキー",
    description:
      "計算結果のキャッシュです。キーとして不適切な行を1つ選んでください。",
    code: [
      "public class LengthCache {",
      "    private final Map<StringBuilder, Integer> cache = new HashMap<>();",
      "",
      "    public int cachedLen(StringBuilder sb) {",
      "        Objects.requireNonNull(sb);",
      "        return cache.computeIfAbsent(sb, s -> s.length());",
      "    }",
      "",
      "    public void clear() {",
      "        cache.clear();",
      "    }",
      "",
      "    public int size() {",
      "        return cache.size();",
      "    }",
      "}",
    ],
    antiPatternLines: [2],
    patternName: "可変な StringBuilder を Map キーに",
    explanation:
      "StringBuilder は可変で、キー向きではありません。equals/hashCode も参照同一性のままで内容での検索ができず、中身を変えたあとの意図しない挙動も招きやすいです。String など不変キーにしましょう。",
    hint: "キーの中身は後から変わり得ますか？",
  },

  // ========== 上級者 追加 (20) ==========
  {
    id: 71,
    difficulty: "advanced",
    title: "可視性の保証",
    description:
      "別スレッドから止めるフラグです。停止要求が見えないことがある読み取り行を1つ選んでください。",
    code: [
      "public class Worker {",
      "    private boolean stopped;",
      "    private final String name;",
      "",
      "    public Worker(String name) {",
      "        this.name = Objects.requireNonNull(name);",
      "    }",
      "",
      "    public void stop() {",
      "        stopped = true;",
      "    }",
      "",
      "    public void run() {",
      "        while (!stopped) {",
      "            work();",
      "        }",
      "    }",
      "",
      "    private void work() {",
      "        // do unit of work",
      "    }",
      "}",
    ],
    antiPatternLines: [14],
    patternName: "同期なしの共有フラグ読み取り",
    explanation:
      "他スレッドが止めた stopped の更新が、同期や volatile なしではループ側から見えないことがあります。volatile や AtomicBoolean を使いましょう。",
    hint: "書き込みは、他スレッドの読み取りに必ず見えますか？",
  },
  {
    id: 72,
    difficulty: "advanced",
    title: "ロックの取り方",
    description:
      "2つの資源を扱う処理です。デッドロックを招きうる行を選んでください。",
    code: [
      "public class TransferService {",
      "    private static final Logger logger = LoggerFactory.getLogger(TransferService.class);",
      "",
      "    public void transfer(Account from, Account to, int amount) {",
      "        Objects.requireNonNull(from);",
      "        Objects.requireNonNull(to);",
      "        if (amount <= 0) throw new IllegalArgumentException(\"amount\");",
      "        synchronized (from) {",
      "            synchronized (to) {",
      "                from.debit(amount);",
      "                to.credit(amount);",
      "                logger.info(\"transferred {}\", amount);",
      "            }",
      "        }",
      "    }",
      "}",
    ],
    antiPatternLines: [8, 9],
    patternName: "順序不定のネストしたロック",
    explanation:
      "A→B と B→A で同時に呼ばれるとデッドロックします。口座 ID などでロック順を一意にしましょう。",
    hint: "逆順で同じメソッドが呼ばれたら？",
  },
  {
    id: 73,
    difficulty: "advanced",
    title: "完了通知",
    description:
      "処理完了を待つコードです。待機と通知の組み合わせとして不十分な行を1つ選んでください。",
    code: [
      "public class CompletionNotifier {",
      "    private volatile boolean done;",
      "",
      "    public void awaitDone() throws InterruptedException {",
      "        synchronized (this) {",
      "            while (!done) {",
      "                wait();",
      "            }",
      "        }",
      "    }",
      "",
      "    public void signalDone() {",
      "        done = true;",
      "        notify();",
      "    }",
      "}",
    ],
    antiPatternLines: [14],
    patternName: "モニタなしの notify",
    explanation:
      "notify / wait は同期中のモニタで呼ぶ必要があります。このままでは IllegalMonitorStateException か、正しい待ちと結びつきません。synchronized 内で呼びましょう。",
    hint: "このオブジェクトのロックは保持していますか？",
  },
  {
    id: 74,
    difficulty: "advanced",
    title: "タスクの打ち切り",
    description:
      "実行中のワーカースレッドを止めようとする処理です。現在の Java では推奨されない行を1つ選んでください。",
    code: [
      "public class TaskCanceller {",
      "    private static final Logger logger = LoggerFactory.getLogger(TaskCanceller.class);",
      "",
      "    public void cancel(Thread worker) {",
      "        if (worker == null) return;",
      "        logger.warn(\"cancelling thread {}\", worker.getName());",
      "        worker.stop();",
      "    }",
      "",
      "    public String describe(Thread worker) {",
      "        return worker == null ? \"null\" : worker.getName();",
      "    }",
      "}",
    ],
    antiPatternLines: [7],
    patternName: "Thread.stop の使用",
    explanation:
      "Thread.stop は非推奨・危険で、オブジェクトを不整合な状態にし得ます。割り込みフラグやキャンセル機構を使いましょう。",
    hint: "この API は今でも推奨されていますか？",
  },
  {
    id: 75,
    difficulty: "advanced",
    title: "カウンタの集計",
    description:
      "キーごとのカウンタをマップで持つ処理です。アトミックでない行を選んでください。",
    code: [
      "public class CounterMap {",
      "    private final ConcurrentHashMap<String, Integer> map = new ConcurrentHashMap<>();",
      "",
      "    public void increment(String key) {",
      "        Objects.requireNonNull(key);",
      "        Integer v = map.get(key);",
      "        if (v == null) {",
      "            map.put(key, 1);",
      "        } else {",
      "            map.put(key, v + 1);",
      "        }",
      "    }",
      "",
      "    public int get(String key) {",
      "        return map.getOrDefault(key, 0);",
      "    }",
      "}",
    ],
    antiPatternLines: [6, 7, 8, 9, 10],
    patternName: "get-then-put の競合",
    explanation:
      "ConcurrentHashMap でも get と put のあいだはアトミックではありません。merge や compute を使いましょう。",
    hint: "読んだ直後に他スレッドが書けませんか？",
  },
  {
    id: 76,
    difficulty: "advanced",
    title: "発行と購読",
    description:
      "リスナー一覧です。複数スレッドから使うときに問題になりうる宣言行を1つ選んでください。",
    code: [
      "public class EventBus {",
      "    private final List<Listener> listeners = new ArrayList<>();",
      "",
      "    public void addListener(Listener listener) {",
      "        listeners.add(Objects.requireNonNull(listener));",
      "    }",
      "",
      "    public void fire() {",
      "        for (Listener listener : listeners) {",
      "            listener.onEvent();",
      "        }",
      "    }",
      "",
      "    public int listenerCount() {",
      "        return listeners.size();",
      "    }",
      "}",
    ],
    antiPatternLines: [2],
    patternName: "非スレッドセーフなリスナーリスト",
    explanation:
      "ArrayList を複数スレッドから変更・走査すると CME や欠落が起きます。CopyOnWriteArrayList や防御的コピーを検討しましょう。",
    hint: "このリストは同時アクセスに向いていますか？",
  },
  {
    id: 77,
    difficulty: "advanced",
    title: "安全でない公開",
    description:
      "ワーカースレッドへオブジェクトを渡す処理です。構築途中が見える行を1つ選んでください。",
    code: [
      "public class Server {",
      "    private Helper helper;",
      "",
      "    public void start() {",
      "        new Thread(() -> helper.use()).start();",
      "        helper = new Helper();",
      "    }",
      "",
      "    public void shutdown() {",
      "        // graceful shutdown",
      "    }",
      "",
      "    static class Helper {",
      "        void use() { /* work */ }",
      "    }",
      "}",
    ],
    antiPatternLines: [5],
    patternName: "初期化前の参照の公開",
    explanation:
      "スレッドを先に起動すると、helper が null のまま、または初期化前に使われる可能性があります。代入してから start するか、コンストラクタで完全に作ってから渡しましょう。",
    hint: "スレッドはいつ helper を見に行きますか？",
  },
  {
    id: 78,
    difficulty: "advanced",
    title: "リクエスト単位の文脈",
    description:
      "スレッドプール上でリクエスト ID を保持する処理です。次のタスクへ値が残るおそれがある片付け方をしている行を1つ選んでください。",
    code: [
      "public class RequestContext {",
      "    private static final ThreadLocal<String> CONTEXT = new ThreadLocal<>();",
      "    private final ExecutorService executor;",
      "",
      "    public RequestContext(ExecutorService executor) {",
      "        this.executor = Objects.requireNonNull(executor);",
      "    }",
      "",
      "    public void runWithContext(String requestId) {",
      "        executor.execute(() -> {",
      "            CONTEXT.set(requestId);",
      "            try {",
      "                handle();",
      "            } finally {",
      "                CONTEXT.set(null);",
      "            }",
      "        });",
      "    }",
      "",
      "    private void handle() { /* business logic */ }",
      "}",
    ],
    antiPatternLines: [15],
    patternName: "プールスレッドでの ThreadLocal 誤片付け",
    explanation:
      "スレッドプールではスレッドが再利用されるため、ThreadLocal は remove() で片付ける必要があります。set(null) ではエントリが残り、次タスクへ漏れます。",
    hint: "null を入れるだけで、前の値は消えますか？",
  },
  {
    id: 79,
    difficulty: "advanced",
    title: "ロックの粒度",
    description:
      "キャッシュ全体を守る処理です。並行性を過度に落とす行を1つ選んでください。",
    code: [
      "public class ItemCache {",
      "    private final Map<String, Item> cache = new HashMap<>();",
      "",
      "    public synchronized Item get(String key) {",
      "        Objects.requireNonNull(key);",
      "        return expensiveLoad(key);",
      "    }",
      "",
      "    private Item expensiveLoad(String key) {",
      "        return cache.computeIfAbsent(key, this::loadFromDb);",
      "    }",
      "",
      "    private Item loadFromDb(String key) {",
      "        return new Item(key);",
      "    }",
      "}",
    ],
    antiPatternLines: [4],
    patternName: "長い処理を synchronized メソッドで直列化",
    explanation:
      "expensiveLoad 全体を同期すると、無関係なキーも待ちます。キー単位のロックや ConcurrentHashMap.compute などを検討しましょう。",
    hint: "別キーの取得も待たされますか？",
  },
  {
    id: 80,
    difficulty: "advanced",
    title: "準備完了の通知",
    description:
      "準備が整ったことを他スレッドへ伝える処理です。待機中のスレッドを起こせない行を1つ選んでください。",
    code: [
      "public class ReadyGate {",
      "    private boolean ready;",
      "",
      "    public synchronized void awaitReady() throws InterruptedException {",
      "        while (!ready) {",
      "            wait();",
      "        }",
      "    }",
      "",
      "    public synchronized void setReady() {",
      "        ready = true;",
      "        wait();",
      "    }",
      "}",
    ],
    antiPatternLines: [12],
    patternName: "notify の代わりに wait を呼ぶ",
    explanation:
      "状態を true にしたあと wait() を呼ぶと、自分自身が待機してしまい、他スレッドを起こせません。notify や notifyAll を使いましょう。",
    hint: "待っているのは自分ですか、他のスレッドですか？",
  },
  {
    id: 81,
    difficulty: "advanced",
    title: "ハッシュと可変",
    description:
      "並列処理向けマップです。キー破壊につながる行を1つ選んでください。",
    code: [
      "static class PayloadKey {",
      "    byte[] bytes;",
      "",
      "    PayloadKey(byte[] bytes) {",
      "        this.bytes = bytes;",
      "    }",
      "",
      "    @Override",
      "    public boolean equals(Object o) {",
      "        return o instanceof PayloadKey k && Arrays.equals(bytes, k.bytes);",
      "    }",
      "",
      "    @Override",
      "    public int hashCode() {",
      "        return Arrays.hashCode(bytes);",
      "    }",
      "}",
      "",
      "public class ByteKeyStore {",
      "    private final ConcurrentHashMap<PayloadKey, String> map = new ConcurrentHashMap<>();",
      "",
      "    public void put(PayloadKey key, String value) {",
      "        Objects.requireNonNull(key);",
      "        Objects.requireNonNull(value);",
      "        map.put(key, value);",
      "        key.bytes[0] = 0;",
      "    }",
      "",
      "    public String get(byte[] bytes) {",
      "        return map.get(new PayloadKey(bytes));",
      "    }",
      "}",
    ],
    antiPatternLines: [26],
    patternName: "put 後のキー配列変更",
    explanation:
      "equals/hashCode が配列内容に依存するのに、put 後に bytes を書き換えるとエントリを見失います。キーは不変オブジェクトにコピーして使いましょう。",
    hint: "キーのバイト列は put 後も同じである必要があります。",
  },
  {
    id: 82,
    difficulty: "advanced",
    title: "リソースの解放通知",
    description:
      "複数スレッドが待機している場面です。待機者のうち一部だけが進める可能性がある行を1つ選んでください。",
    code: [
      "public class ResourcePool {",
      "    private boolean condition;",
      "",
      "    public synchronized void awaitResource() throws InterruptedException {",
      "        while (!condition) {",
      "            wait();",
      "        }",
      "    }",
      "",
      "    public synchronized void releaseOne() {",
      "        condition = true;",
      "        notify();",
      "    }",
      "}",
    ],
    antiPatternLines: [12],
    patternName: "複数待機での notify 単発",
    explanation:
      "notify は待機中の1スレッドだけを起こします。条件を待つスレッドが複数なら notifyAll が安全です（意図的な単発以外）。",
    hint: "待っているのが2人以上だと？",
  },
  {
    id: 83,
    difficulty: "advanced",
    title: "安全な公開",
    description:
      "オブジェクトを他スレッドへ渡す処理です。未初期化が見える行を1つ選んでください。",
    code: [
      "public class Publisher {",
      "    public void publish() {",
      "        Holder.h = new Holder(42);",
      "    }",
      "",
      "    public Holder current() {",
      "        return Holder.h;",
      "    }",
      "",
      "    static class Holder {",
      "        static Holder h;",
      "        final int value;",
      "        Holder(int value) { this.value = value; }",
      "    }",
      "}",
    ],
    antiPatternLines: [3],
    patternName: "同期なしのオブジェクト公開",
    explanation:
      "static フィールドへの代入だけでは、他スレッドが value の初期化を見ない可能性があります。volatile や final フィールド、安全な公開手段を使いましょう。",
    hint: "参照が見えたとき、中のフィールドも見えますか？",
  },
  {
    id: 84,
    difficulty: "advanced",
    title: "割り込み後の継続",
    description:
      "タスク実行ループです。割り込みを無視している行を1つ選んでください。",
    code: [
      "public class QueueWorker {",
      "    private static final Logger log = LoggerFactory.getLogger(QueueWorker.class);",
      "    private final BlockingQueue<Task> queue;",
      "",
      "    public QueueWorker(BlockingQueue<Task> queue) {",
      "        this.queue = Objects.requireNonNull(queue);",
      "    }",
      "",
      "    public void loop() {",
      "        while (true) {",
      "            try {",
      "                queue.take();",
      "            } catch (InterruptedException e) {",
      "                log.warn(\"interrupted\");",
      "            }",
      "        }",
      "    }",
      "}",
    ],
    antiPatternLines: [14],
    patternName: "割り込みを無視してループ継続",
    explanation:
      "InterruptedException をログだけしてループを続けると、割り込み状態も復元されずシャットダウンできません。interrupt を復元するか、ループを抜けるべきです。",
    hint: "キャンセル要求はどこへ行きますか？",
  },
  {
    id: 85,
    difficulty: "advanced",
    title: "タスクの待ち合わせ",
    description:
      "非同期結果を待つ処理です。応答なしで固まりうる行を1つ選んでください。",
    code: [
      "public class ResultFetcher {",
      "    private final ExecutorService executor;",
      "",
      "    public ResultFetcher(ExecutorService executor) {",
      "        this.executor = Objects.requireNonNull(executor);",
      "    }",
      "",
      "    public Result fetch() throws Exception {",
      "        Future<Result> future = executor.submit(this::load);",
      "        return future.get();",
      "    }",
      "",
      "    private Result load() {",
      "        return new Result(\"ok\");",
      "    }",
      "}",
    ],
    antiPatternLines: [10],
    patternName: "タイムアウトなしの Future#get",
    explanation:
      "タイムアウトなしの get は、タスクが終わらないとスレッドを永久にブロックします。get(timeout, unit) やキャンセル方針を決めましょう。",
    hint: "相手が返ってこなかったら？",
  },
  {
    id: 86,
    difficulty: "advanced",
    title: "リストへの収集",
    description:
      "共有リストへ書き込む処理です。データ破壊を招く行を1つ選んでください。",
    code: [
      "public class ParallelCollector {",
      "    public List<String> collect(List<String> src) {",
      "        if (src == null) return List.of();",
      "        List<String> out = new ArrayList<>();",
      "        src.parallelStream().forEach(out::add);",
      "        return out;",
      "    }",
      "",
      "    public boolean isEmpty(List<String> src) {",
      "        return src == null || src.isEmpty();",
      "    }",
      "}",
    ],
    antiPatternLines: [5],
    patternName: "並列ストリームから非スレッドセーフ List へ",
    explanation:
      "ArrayList はスレッドセーフでないため、parallelStream からの add で壊れます。collect(Collectors.toList()) などを使いましょう。",
    hint: "複数スレッドが同時に add していますか？",
  },
  {
    id: 87,
    difficulty: "advanced",
    title: "ロックの解放",
    description:
      "明示的ロックを使う処理です。解放漏れにつながる行を1つ選んでください。",
    code: [
      "public class LockWorker {",
      "    private final ReentrantLock lock = new ReentrantLock();",
      "",
      "    public void critical() {",
      "        lock.lock();",
      "        try {",
      "            work();",
      "        }",
      "        lock.unlock();",
      "    }",
      "",
      "    private void work() {",
      "        // critical section",
      "    }",
      "}",
    ],
    antiPatternLines: [9],
    patternName: "finally なしの unlock",
    explanation:
      "unlock() が try の外にあると、work() が例外を投げたときにロックが解放されません。try-finally で unlock しましょう。",
    hint: "work が例外を投げたら unlock は走りますか？",
  },
  {
    id: 88,
    difficulty: "advanced",
    title: "完了の合図",
    description:
      "完了フラグと待機解除を行う処理です。待ち側が再び待ちに入ってしまうおそれがある行を選んでください。",
    code: [
      "public class CompletionFlag {",
      "    private boolean done;",
      "",
      "    public synchronized void awaitDone() throws InterruptedException {",
      "        while (!done) {",
      "            wait();",
      "        }",
      "    }",
      "",
      "    public void complete() {",
      "        synchronized (this) {",
      "            notifyAll();",
      "            done = true;",
      "        }",
      "    }",
      "}",
    ],
    antiPatternLines: [12, 13],
    patternName: "notify してからフラグを立てる",
    explanation:
      "先に notify すると、起き上がったスレッドがまだ done==false を見ることがあります。先に状態を更新してから notifyAll しましょう。",
    hint: "起こされた直後、条件はすでに真ですか？",
  },
  {
    id: 89,
    difficulty: "advanced",
    title: "バックグラウンド起動",
    description:
      "バックグラウンド処理の起動です。途中で強制終了されうる行を1つ選んでください。",
    code: [
      "public class BackgroundStarter {",
      "    private static final Logger logger = LoggerFactory.getLogger(BackgroundStarter.class);",
      "",
      "    public void startWorker(Runnable task) {",
      "        Objects.requireNonNull(task);",
      "        Thread t = new Thread(task);",
      "        t.setDaemon(true);",
      "        t.setName(\"bg-worker\");",
      "        t.start();",
      "        logger.info(\"worker started\");",
      "    }",
      "}",
    ],
    antiPatternLines: [7],
    patternName: "重要な作業のデーモンスレッド化",
    explanation:
      "デーモンスレッドは JVM 終了時に強制停止され、書き込み途中などが壊れ得ます。必須作業は非デーモンにするか、明示的なシャットダウンを設計しましょう。",
    hint: "メインが終わると、このスレッドはどうなりますか？",
  },
  {
    id: 90,
    difficulty: "advanced",
    title: "クラス初期化",
    description:
      "設定の読み込みです。デッドロックや初期化失敗を招きうる行を選んでください。",
    code: [
      "public class Config {",
      "    static final Config INSTANCE = load();",
      "    private final String env;",
      "",
      "    private Config(String env) {",
      "        this.env = env;",
      "    }",
      "",
      "    static Config load() {",
      "        return Factory.create();",
      "    }",
      "",
      "    public String getEnv() {",
      "        return env;",
      "    }",
      "}",
      "",
      "class Factory {",
      "    static Config create() {",
      "        return Config.INSTANCE;",
      "    }",
      "}",
    ],
    antiPatternLines: [2, 19],
    patternName: "クラス初期化中の循環参照",
    explanation:
      "Config の初期化中に Factory が Config.INSTANCE を参照すると、未初期化のまま戻ったり初期化デッドロックの原因になります。初期化を単純で一方向に保ちましょう。",
    hint: "INSTANCE が完成する前に、誰かがそれを読んでいませんか？",
  },
];
