import { moreQuestions } from "./moreQuestions";
import type { Difficulty, QuizQuestion } from "./quizTypes";
import { isIgnorableLine } from "./quizUtils";

export type { Difficulty, QuizQuestion } from "./quizTypes";
export { isIgnorableLine } from "./quizUtils";

export function getSelectionGuide(question: QuizQuestion): string {
  if (question.antiPatternLines.length === 1) {
    return "該当する行を1つ選んでください。";
  }
  return "該当する行を選んでください。同種の問題が複数ある場合は、1行でもすべてでも構いません。";
}

/**
 * 採点: 正解行を1行以上含み、かつ正解以外の実質的な行を選んでいなければ正解。
 * 完全一致は求めない（同種の複数行は代表1行でも可）。
 */
export function isSelectionCorrect(
  selected: Set<number>,
  answerLines: number[],
  code: string[],
): boolean {
  if (selected.size === 0) return false;

  const answers = new Set(answerLines);
  let hit = false;

  for (const line of selected) {
    if (answers.has(line)) {
      hit = true;
      continue;
    }
    const content = code[line - 1] ?? "";
    if (isIgnorableLine(content)) continue;
    return false;
  }

  return hit;
}

export const DIFFICULTY_META: Record<
  Difficulty,
  { label: string; description: string; color: string }
> = {
  beginner: {
    label: "初心者",
    description: "文法・基本的な落とし穴",
    color: "beginner",
  },
  intermediate: {
    label: "中級者",
    description: "設計・API・よくある実務ミス",
    color: "intermediate",
  },
  advanced: {
    label: "上級者",
    description: "並行性・高度な落とし穴",
    color: "advanced",
  },
};

export const questions: QuizQuestion[] = [
  // ========== 初心者 (30) ==========
  {
    id: 1,
    difficulty: "beginner",
    title: "文字列の比較",
    description:
      "ユーザー名を検証するメソッドです。意図どおりに動かないことがある比較処理を含む行を1つ選んでください。",
    code: [
      "public class AuthService {",
      "    private static final Logger log = LoggerFactory.getLogger(AuthService.class);",
      "    private final Set<String> elevatedUsers = Set.of(\"superuser\");",
      "",
      "    public boolean isAdmin(String username) {",
      "        if (username == null) {",
      "            return false;",
      "        }",
      "        log.debug(\"Checking admin status for: {}\", username);",
      "        if (username == \"admin\") {",
      "            return true;",
      "        }",
      "        return elevatedUsers.contains(username);",
      "    }",
      "}",
    ],
    antiPatternLines: [10],
    patternName: "== による String 比較",
    explanation:
      "String の内容比較には == ではなく equals() を使います。== は参照の同一性を比較するため、意図しない結果になります。",
    hint: "オブジェクトの等価性と参照の同一性は別物です。",
  },
  {
    id: 2,
    difficulty: "beginner",
    title: "年齢グループの判定",
    description:
      "ユーザーの年齢を判定するメソッドです。可読性・保守性の観点でアンチパターンの行を選んでください。",
    code: [
      "public class AgeService {",
      "    private static final Logger log = LoggerFactory.getLogger(AgeService.class);",
      "",
      "    public String getAgeGroup(int age) {",
      "        if (age < 0) {",
      "            throw new IllegalArgumentException(\"age must be non-negative\");",
      "        }",
      "        log.trace(\"Grouping age: {}\", age);",
      "        if (age < 20) {",
      "            return \"teen\";",
      "        } else if (age < 65) {",
      "            return \"adult\";",
      "        }",
      "        return \"senior\";",
      "    }",
      "}",
    ],
    antiPatternLines: [9, 11],
    patternName: "マジックナンバー",
    explanation:
      "20 や 65 といった意味のある数値がコード中に直接書かれています。定数として名前を付け、意図を明確にすべきです。",
    hint: "この数字は何を表していますか？",
  },
  {
    id: 3,
    difficulty: "beginner",
    title: "ログの組み立て",
    description:
      "大量のログ項目からテキストを組み立てる処理です。繰り返し処理の中で、効率面で問題になりうる行を1つ選んでください。",
    code: [
      "public class LogBuilder {",
      "    private static final Logger log = LoggerFactory.getLogger(LogBuilder.class);",
      "",
      "    public String buildLog(List<String> items) {",
      "        if (items == null || items.isEmpty()) {",
      "            return \"\";",
      "        }",
      "        String result = \"\";",
      "        for (String item : items) {",
      "            result = result + item + \",\";",
      "        }",
      "        log.debug(\"Built log from {} items\", items.size());",
      "        return result.substring(0, result.length() - 1);",
      "    }",
      "}",
    ],
    antiPatternLines: [10],
    patternName: "ループ内での String 連結",
    explanation:
      "ループ内で + による文字列連結を繰り返すと、毎回新しい String が生成されます。StringBuilder や String.join() を使いましょう。",
    hint: "不変オブジェクトを繰り返し作り直していませんか？",
  },
  {
    id: 4,
    difficulty: "beginner",
    title: "ファイルの読み取り",
    description:
      "ファイル読み込み処理です。失敗時の扱いとして、呼び出し側が成功と混同しうる行を選んでください。",
    code: [
      "public class FileReaderService {",
      "    private static final Logger log = LoggerFactory.getLogger(FileReaderService.class);",
      "",
      "    public String readFile(Path path) {",
      "        Objects.requireNonNull(path, \"path\");",
      "        try {",
      "            String content = Files.readString(path, StandardCharsets.UTF_8);",
      "            log.info(\"Read {} bytes from {}\", content.length(), path);",
      "            return content;",
      "        } catch (IOException e) {",
      "            return \"\";",
      "        }",
      "    }",
      "}",
    ],
    antiPatternLines: [11],
    patternName: "例外の握りつぶし",
    explanation:
      "catch 内で空文字を返すと、読み込み失敗を成功のように見せてしまいます。ログ出力・再スロー・適切な代替処理を行いましょう。",
    hint: "失敗を成功のように見せていませんか？",
  },
  {
    id: 5,
    difficulty: "beginner",
    title: "ユーザー検索",
    description:
      "ユーザーを検索するメソッドです。呼び出し側の安全性を損ないうる戻り方をしている行を1つ選んでください。",
    code: [
      "public class UserRepository {",
      "    private static final Logger log = LoggerFactory.getLogger(UserRepository.class);",
      "    private final List<User> users;",
      "",
      "    public UserRepository(List<User> users) {",
      "        this.users = new ArrayList<>(users);",
      "    }",
      "",
      "    public User findUserById(Long id) {",
      "        Objects.requireNonNull(id, \"id\");",
      "        log.debug(\"Searching user with id: {}\", id);",
      "        for (User user : users) {",
      "            if (Objects.equals(user.getId(), id)) {",
      "                log.info(\"Found user: {}\", user.getName());",
      "                return user;",
      "            }",
      "        }",
      "        log.warn(\"User not found: {}\", id);",
      "        return null;",
      "    }",
      "}",
    ],
    antiPatternLines: [19],
    patternName: "null の返却",
    explanation:
      "見つからない場合に null を返すと、呼び出し側で NullPointerException が起きやすくなります。Optional<User> を返すか、例外を投げる設計が推奨されます。",
    hint: "呼び出し側は毎回 null チェックが必要になります。",
  },
  {
    id: 6,
    difficulty: "beginner",
    title: "ログの出し方",
    description:
      "エラー情報を出力する処理です。運用上好ましくない出力方法を使っている行を1つ選んでください。",
    code: [
      "public class ErrorHandler {",
      "    private static final Logger log = LoggerFactory.getLogger(ErrorHandler.class);",
      "",
      "    public void handleError(String operation, Exception e) {",
      "        if (e == null) {",
      "            return;",
      "        }",
      "        System.out.println(\"Error: \" + e.getMessage());",
      "        notifyMonitoring(operation, e);",
      "    }",
      "",
      "    private void notifyMonitoring(String operation, Exception e) {",
      "        // monitoring integration",
      "    }",
      "}",
    ],
    antiPatternLines: [8],
    patternName: "System.out によるログ出力",
    explanation:
      "本番コードでは System.out / System.err ではなく、ロギングフレームワーク（SLF4J など）を使います。ログレベル・出力先・フォーマットを制御できないためです。",
    hint: "本番環境で標準出力に頼るのは適切ですか？",
  },
  {
    id: 7,
    difficulty: "beginner",
    title: "回答の判定",
    description:
      "アンケート回答を判定する処理です。引数が null のときに実行時例外になりうる行を1つ選んでください。",
    code: [
      "public class SurveyService {",
      "    private static final Logger log = LoggerFactory.getLogger(SurveyService.class);",
      "    private static final String YES_VALUE = \"yes\";",
      "",
      "    public boolean isYes(String input) {",
      "        log.debug(\"Validating response: {}\", input);",
      "        return input.equals(YES_VALUE);",
      "    }",
      "",
      "    public boolean matchesCategory(String input, String category) {",
      "        if (input == null || category == null) {",
      "            return false;",
      "        }",
      "        return category.equals(input.trim());",
      "    }",
      "}",
    ],
    antiPatternLines: [7],
    patternName: "null になりうるオブジェクトへの equals",
    explanation:
      "input が null のとき NPE になります。\"yes\".equals(input) とするか、Objects.equals(input, \"yes\") を使いましょう。",
    hint: "引数が null だったらどうなりますか？",
  },
  {
    id: 8,
    difficulty: "beginner",
    title: "数値の比較",
    description:
      "計算結果を比較する処理です。数値の性質を考慮していない比較をしている行を1つ選んでください。",
    code: [
      "public class CalcUtil {",
      "    private static final Logger log = LoggerFactory.getLogger(CalcUtil.class);",
      "",
      "    public boolean isOne(double value) {",
      "        log.trace(\"Checking if {} equals 1.0\", value);",
      "        return value == 1.0;",
      "    }",
      "",
      "    public String label(double value) {",
      "        return \"value=\" + value;",
      "    }",
      "}",
    ],
    antiPatternLines: [6],
    patternName: "浮動小数点の == 比較",
    explanation:
      "double / float は誤差があるため == での等価比較は危険です。許容誤差を決めて Math.abs(a - b) < epsilon のように比較します。",
    hint: "0.1 + 0.2 はちょうど 0.3 になりますか？",
  },
  {
    id: 9,
    difficulty: "beginner",
    title: "分岐のつながり",
    description:
      "ステータスに応じてメッセージを返す処理です。意図しない分岐につながる行を1つ選んでください。",
    code: [
      "public class StatusLabeler {",
      "    private static final Logger log = LoggerFactory.getLogger(StatusLabeler.class);",
      "",
      "    public String label(int status) {",
      "        log.debug(\"Resolving label for status: {}\", status);",
      "        String pending = null;",
      "        switch (status) {",
      "            case 1:",
      "                return \"OK\";",
      "            case 2:",
      "                pending = \"WARN\";",
      "            case 3:",
      "                return pending != null ? pending : \"NG\";",
      "            default:",
      "                log.warn(\"Unknown status: {}\", status);",
      "                return \"UNKNOWN\";",
      "        }",
      "    }",
      "}",
    ],
    antiPatternLines: [11],
    patternName: "break / return 忘れによるフォールスルー",
    explanation:
      "case 2 で return も break もないため、pending を設定したあと case 3 に落ちて意図しない戻り値になります。各 case を明示的に終了させましょう。",
    hint: "case 2 の処理のあと、switch はどこへ進みますか？",
  },
  {
    id: 10,
    difficulty: "beginner",
    title: "フィールドの公開範囲",
    description:
      "ユーザー情報を表すクラスです。カプセル化を破る行を選んでください。",
    code: [
      "public class User {",
      "    public String name;",
      "    public int age;",
      "",
      "    public User(String name, int age) {",
      "        this.name = name;",
      "        this.age = age;",
      "    }",
      "",
      "    public String displayName() {",
      "        return name + \" (\" + age + \")\";",
      "    }",
      "}",
    ],
    antiPatternLines: [2, 3],
    patternName: "public な可変フィールド",
    explanation:
      "フィールドを public にすると、どこからでも直接変更でき、不変条件を守れません。private にして getter / setter（または不変オブジェクト）で公開しましょう。",
    hint: "外部から好きに書き換えられていませんか？",
  },

  // ========== 中級者 (30) ==========
  {
    id: 11,
    difficulty: "intermediate",
    title: "リソースの寿命",
    description:
      "データベース接続を使う処理です。リソースリークにつながる行を選んでください。",
    code: [
      "public class DataExporter {",
      "    private static final Logger log = LoggerFactory.getLogger(DataExporter.class);",
      "",
      "    public void exportData(Connection conn) throws SQLException {",
      "        log.info(\"Starting user export\");",
      "        Statement stmt = conn.createStatement();",
      "        ResultSet rs = stmt.executeQuery(\"SELECT * FROM users\");",
      "        int count = 0;",
      "        while (rs.next()) {",
      "            String name = rs.getString(\"name\");",
      "            log.debug(\"Exporting: {}\", name);",
      "            count++;",
      "        }",
      "        log.info(\"Exported {} users\", count);",
      "    }",
      "}",
    ],
    antiPatternLines: [6, 7],
    patternName: "リソースの未クローズ",
    explanation:
      "このメソッドで生成した Statement と ResultSet はクローズされていません。try-with-resources で囲みましょう。（引数の Connection は呼び出し側の管理対象です。）",
    hint: "このメソッドで開いたリソースは閉じる責務があります。",
  },
  {
    id: 12,
    difficulty: "intermediate",
    title: "共有される設定値",
    description:
      "設定値を保持するクラスです。カプセル化を破る行を選んでください。",
    code: [
      "public class AppConfig {",
      "    private static final Logger log = LoggerFactory.getLogger(AppConfig.class);",
      "",
      "    public static int MAX_RETRY = 3;",
      "    public static boolean DEBUG_MODE = true;",
      "",
      "    public static void logSettings() {",
      "        log.info(\"MAX_RETRY={}, DEBUG_MODE={}\", MAX_RETRY, DEBUG_MODE);",
      "    }",
      "}",
    ],
    antiPatternLines: [4, 5],
    patternName: "可変な public static フィールド",
    explanation:
      "public static かつ可変なフィールドはグローバル変数のようにどこからでも変更でき、予測不能になります。",
    hint: "グローバル変数のような状態は危険です。",
  },
  {
    id: 13,
    difficulty: "intermediate",
    title: "コレクションの型",
    description:
      "コレクションを扱うコードです。型安全性を失う原因となっている宣言行を1つ選んでください。",
    code: [
      "public class ItemProcessor {",
      "    private static final Logger log = LoggerFactory.getLogger(ItemProcessor.class);",
      "",
      "    public void processItems() {",
      "        List items = new ArrayList();",
      "        items.add(\"hello\");",
      "        items.add(42);",
      "        log.debug(\"Processing {} items\", items.size());",
      "        String first = (String) items.get(0);",
      "        log.info(\"First item: {}\", first);",
      "    }",
      "}",
    ],
    antiPatternLines: [5],
    patternName: "Raw Type の使用",
    explanation:
      "ジェネリクスを省略した List items = new ArrayList() は Raw Type です。異種追加やキャストの原因になります。List<String> のように型引数を指定しましょう。",
    hint: "後続の問題は、どの宣言から生じていますか？",
  },
  {
    id: 14,
    difficulty: "intermediate",
    title: "equals の実装",
    description:
      "値オブジェクトの equals 実装です。実行時エラーを招きうる行を1つ選んでください。",
    code: [
      "public class Item {",
      "    private final String id;",
      "",
      "    public Item(String id) {",
      "        this.id = Objects.requireNonNull(id);",
      "    }",
      "",
      "    public String getId() {",
      "        return id;",
      "    }",
      "",
      "    @Override",
      "    public boolean equals(Object obj) {",
      "        Item other = (Item) obj;",
      "        return Objects.equals(this.id, other.id);",
      "    }",
      "",
      "    @Override",
      "    public int hashCode() {",
      "        return Objects.hash(id);",
      "    }",
      "}",
    ],
    antiPatternLines: [14],
    patternName: "instanceof チェックなしのキャスト",
    explanation:
      "equals ではキャスト前に instanceof で型を確認する必要があります。確認なしの (Item) obj は ClassCastException を起こします。",
    hint: "null や別の型が渡されたときどうなりますか？",
  },
  {
    id: 15,
    difficulty: "intermediate",
    title: "例外の捕捉範囲",
    description:
      "ネットワーク処理です。例外の取り扱いとして広すぎる行を1つ選んでください。",
    code: [
      "public class ApiClient {",
      "    private static final Logger log = LoggerFactory.getLogger(ApiClient.class);",
      "    private final HttpClient client;",
      "    private final HttpRequest request;",
      "",
      "    public ApiClient(HttpClient client, HttpRequest request) {",
      "        this.client = client;",
      "        this.request = request;",
      "    }",
      "",
      "    public void fetch() {",
      "        log.debug(\"Sending request to {}\", request.uri());",
      "        try {",
      "            client.send(request);",
      "            log.info(\"Request completed successfully\");",
      "        } catch (Exception e) {",
      "            log.warn(\"failed\", e);",
      "        }",
      "    }",
      "}",
    ],
    antiPatternLines: [16],
    patternName: "Exception の一括キャッチ",
    explanation:
      "Exception をまとめて捕まえると、想定外の実行時例外やプログラミングエラーまで握りつぶしやすくなります。扱う例外を具体的に書きましょう。",
    hint: "本当にすべての Exception を同じ扱いしてよいですか？",
  },
  {
    id: 16,
    difficulty: "intermediate",
    title: "内部コレクションの露出",
    description:
      "メンバー一覧を返すメソッドです。内部状態が外から変更できてしまう行を1つ選んでください。",
    code: [
      "public class Team {",
      "    private static final Logger log = LoggerFactory.getLogger(Team.class);",
      "    private final List<String> members = new ArrayList<>();",
      "",
      "    public void addMember(String name) {",
      "        Objects.requireNonNull(name);",
      "        members.add(name);",
      "        log.debug(\"Added member: {}\", name);",
      "    }",
      "",
      "    public List<String> getMembers() {",
      "        return members;",
      "    }",
      "",
      "    public int size() {",
      "        return members.size();",
      "    }",
      "}",
    ],
    antiPatternLines: [12],
    patternName: "可変内部状態の直接返却",
    explanation:
      "内部の List をそのまま返すと、呼び出し側が add/remove できて不変条件が壊れます。Collections.unmodifiableList や防御的コピーを返しましょう。",
    hint: "返したリストは外から変更できませんか？",
  },
  {
    id: 17,
    difficulty: "intermediate",
    title: "ラップ型の比較",
    description:
      "ID を比較する処理です。オブジェクトの比較として問題のある行を1つ選んでください。",
    code: [
      "public class IdMatcher {",
      "    private static final Logger log = LoggerFactory.getLogger(IdMatcher.class);",
      "",
      "    public boolean sameId(Integer a, Integer b) {",
      "        if (a == null || b == null) {",
      "            log.debug(\"Null id comparison: a={}, b={}\", a, b);",
      "            return a == b;",
      "        }",
      "        log.trace(\"Comparing ids: {} vs {}\", a, b);",
      "        return a == b;",
      "    }",
      "}",
    ],
    antiPatternLines: [10],
    patternName: "Integer の == 比較",
    explanation:
      "Integer の == は参照比較です。-128〜127 以外では別インスタンスになりやすく、意図しない false になります。Objects.equals(a, b) や equals を使いましょう。",
    hint: "オートボクシング後の参照は常に同一ですか？",
  },
  {
    id: 18,
    difficulty: "intermediate",
    title: "クエリの組み立て",
    description:
      "ユーザー検索のクエリ組み立てです。セキュリティ上問題のある行を1つ選んでください。",
    code: [
      "public class UserDao {",
      "    private static final Logger log = LoggerFactory.getLogger(UserDao.class);",
      "    private final Connection conn;",
      "",
      "    public UserDao(Connection conn) {",
      "        this.conn = conn;",
      "    }",
      "",
      "    public User findByName(String name) throws SQLException {",
      "        Objects.requireNonNull(name, \"name\");",
      "        String sql = \"SELECT * FROM users WHERE name = '\" + name + \"'\";",
      "        log.debug(\"Executing query for name: {}\", name);",
      "        try (Statement stmt = conn.createStatement();",
      "             ResultSet rs = stmt.executeQuery(sql)) {",
      "            if (rs.next()) {",
      "                return mapRow(rs);",
      "            }",
      "            return null;",
      "        }",
      "    }",
      "",
      "    private User mapRow(ResultSet rs) throws SQLException {",
      "        return new User(rs.getLong(\"id\"), rs.getString(\"name\"));",
      "    }",
      "}",
    ],
    antiPatternLines: [11],
    patternName: "SQL インジェクション（文字列連結）",
    explanation:
      "ユーザー入力を SQL に直接連結すると SQL インジェクションの危険があります。PreparedStatement のプレースホルダを使いましょう。",
    hint: "name に悪意ある文字列が入ったら？",
  },
  {
    id: 19,
    difficulty: "intermediate",
    title: "キャッシュ登録",
    description:
      "キーと値をキャッシュに登録する処理です。登録後に検索できなくなるおそれがある行を1つ選んでください。",
    code: [
      "static class CacheKey {",
      "    int id;",
      "",
      "    CacheKey(int id) {",
      "        this.id = id;",
      "    }",
      "",
      "    @Override",
      "    public boolean equals(Object o) {",
      "        return o instanceof CacheKey k && id == k.id;",
      "    }",
      "",
      "    @Override",
      "    public int hashCode() {",
      "        return Integer.hashCode(id);",
      "    }",
      "}",
      "",
      "public class CacheService {",
      "    private static final Logger log = LoggerFactory.getLogger(CacheService.class);",
      "    private final Map<CacheKey, String> cache = new HashMap<>();",
      "",
      "    public void put(CacheKey key, String value) {",
      "        Objects.requireNonNull(key);",
      "        cache.put(key, value);",
      "        key.id = 0;",
      "        log.debug(\"Cached value for key id={}\", key.id);",
      "    }",
      "",
      "    public String get(int id) {",
      "        return cache.get(new CacheKey(id));",
      "    }",
      "}",
    ],
    antiPatternLines: [26],
    patternName: "可変オブジェクトを Map のキーに変更",
    explanation:
      "HashMap のキーは put 後にハッシュ値が変わってはいけません。equals/hashCode が id 依存なのに key.id を書き換えると、元の id ではエントリを探せなくなります。キーは不変オブジェクトにしましょう。",
    hint: "put のあとキーの中身を変えていませんか？",
  },
  {
    id: 20,
    difficulty: "intermediate",
    title: "オブジェクトの表示",
    description:
      "注文オブジェクトを文字列化する処理です。ログやデバッガから呼ばれることを踏まえ、役割として好ましくない行を1つ選んでください。",
    code: [
      "public class Order {",
      "    private static final Logger log = LoggerFactory.getLogger(Order.class);",
      "    private final long id;",
      "    private final ItemRepository repository;",
      "",
      "    public Order(long id, ItemRepository repository) {",
      "        this.id = id;",
      "        this.repository = repository;",
      "    }",
      "",
      "    public long getId() {",
      "        return id;",
      "    }",
      "",
      "    @Override",
      "    public String toString() {",
      "        return \"Order(\" + id + \", items=\" + repository.findItems(id) + \")\";",
      "    }",
      "}",
    ],
    antiPatternLines: [17],
    patternName: "toString 内の副作用・重い処理",
    explanation:
      "toString はログやデバッガから頻繁に呼ばれます。DB アクセスなどの副作用や重い処理を入れると、性能劣化や想定外の例外を招きます。",
    hint: "ログ出力のたびに DB に問い合わせていませんか？",
  },

  // ========== 上級者 (30) ==========
  {
    id: 21,
    difficulty: "advanced",
    title: "割り込みの扱い",
    description:
      "スレッドを待機する処理です。割り込みを正しく扱えていない行を1つ選んでください。",
    code: [
      "public class TaskWaiter {",
      "    private static final Logger log = LoggerFactory.getLogger(TaskWaiter.class);",
      "",
      "    public void waitForTask() {",
      "        log.debug(\"Waiting for background task...\");",
      "        try {",
      "            Thread.sleep(1000);",
      "            log.info(\"Task wait completed\");",
      "        } catch (InterruptedException e) {",
      "            e.printStackTrace();",
      "        }",
      "    }",
      "}",
    ],
    antiPatternLines: [10],
    patternName: "InterruptedException の握りつぶし",
    explanation:
      "InterruptedException をキャッチしたら、Thread.currentThread().interrupt() で割り込み状態を復元するか、上位に伝播させるべきです。",
    hint: "スレッドの割り込みフラグはどうなりますか？",
  },
  {
    id: 22,
    difficulty: "advanced",
    title: "遅延初期化",
    description:
      "遅延初期化のシングルトンです。複数スレッドで問題になりうる判定の行を1つ選んでください。",
    code: [
      "public class HelperFactory {",
      "    private static final Logger log = LoggerFactory.getLogger(HelperFactory.class);",
      "    private static Helper helper;",
      "",
      "    public static Helper getHelper() {",
      "        if (helper == null) {",
      "            synchronized (HelperFactory.class) {",
      "                helper = new Helper();",
      "                log.info(\"Helper instance created\");",
      "            }",
      "        }",
      "        return helper;",
      "    }",
      "}",
    ],
    antiPatternLines: [6],
    patternName: "ロック外での初期化判定",
    explanation:
      "null かどうかの判定が synchronized の外にあるため、複数スレッドが同時に生成したり、他スレッドの書き込みが見えないことがあります。判定と生成を同じロック内で行うか、ホルダークラス／enum シングルトンを使いましょう。",
    hint: "「まだ無い」と判断している場所は、ロックの内側ですか？",
  },
  {
    id: 23,
    difficulty: "advanced",
    title: "残高の更新",
    description:
      "残高チェック後に出金する処理です。スレッドセーフでない原因の行を選んでください。",
    code: [
      "public class BankAccount {",
      "    private static final Logger log = LoggerFactory.getLogger(BankAccount.class);",
      "    private int balance;",
      "",
      "    public BankAccount(int initialBalance) {",
      "        this.balance = initialBalance;",
      "    }",
      "",
      "    public int getBalance() {",
      "        return balance;",
      "    }",
      "",
      "    public void withdraw(int amount) {",
      "        log.debug(\"Withdraw request: {} (balance={})\", amount, balance);",
      "        if (balance >= amount) {",
      "            balance -= amount;",
      "            log.info(\"Withdrawn {}. New balance: {}\", amount, balance);",
      "        } else {",
      "            log.warn(\"Insufficient funds for withdrawal: {}\", amount);",
      "        }",
      "    }",
      "}",
    ],
    antiPatternLines: [15, 16],
    patternName: "非アトミックな check-then-act",
    explanation:
      "残高確認と減算の間に他スレッドが割り込むと、残高が負になり得ます。synchronized や AtomicInteger、ロックで一連の操作をアトミックにしましょう。",
    hint: "if と代入のあいだに何が起き得ますか？",
  },
  {
    id: 24,
    difficulty: "advanced",
    title: "完了待ち",
    description:
      "準備完了フラグが立つまで待つ処理です。待機中に条件が変わるケースを考慮できていない行を1つ選んでください。",
    code: [
      "public class ReadyFlag {",
      "    private static final Logger log = LoggerFactory.getLogger(ReadyFlag.class);",
      "    private boolean ready;",
      "",
      "    public synchronized void awaitReady() throws InterruptedException {",
      "        log.debug(\"Awaiting ready signal...\");",
      "        if (!ready) {",
      "            wait();",
      "        }",
      "        log.info(\"Ready signal received\");",
      "    }",
      "",
      "    public synchronized void setReady() {",
      "        this.ready = true;",
      "        notifyAll();",
      "    }",
      "}",
    ],
    antiPatternLines: [7],
    patternName: "wait を if で呼ぶ",
    explanation:
      "wait はスプリアスウェイクアップや通知の取りこぼしがあるため、条件が満たされるまで while ループで待つ必要があります。if では不十分です。",
    hint: "一度起きたら条件は必ず真ですか？",
  },
  {
    id: 25,
    difficulty: "advanced",
    title: "リストの整理",
    description:
      "リクエストで受け取った文字列リストを整える処理です。実行時例外を招きうる行を1つ選んでください。",
    code: [
      "public class ListCleaner {",
      "    private static final Logger log = LoggerFactory.getLogger(ListCleaner.class);",
      "",
      "    public void removeInvalid(List<String> items) {",
      "        Objects.requireNonNull(items);",
      "        log.debug(\"Cleaning list of {} items\", items.size());",
      "        for (String item : items) {",
      "            if (item == null) {",
      "                continue;",
      "            }",
      "            if (item.isEmpty()) {",
      "                items.remove(item);",
      "            }",
      "        }",
      "        log.info(\"Cleanup complete. Remaining: {}\", items.size());",
      "    }",
      "",
      "    public int sizeOrZero(List<String> items) {",
      "        return items == null ? 0 : items.size();",
      "    }",
      "}",
    ],
    antiPatternLines: [12],
    patternName: "拡張 for 中のコレクション変更",
    explanation:
      "拡張 for（イテレータ）の走査中に List.remove すると ConcurrentModificationException になります。Iterator.remove() や removeIf を使いましょう。",
    hint: "イテレータで見ている最中に、同じリストの構造を変えていませんか？",
  },
  {
    id: 26,
    difficulty: "advanced",
    title: "日付フォーマット",
    description:
      "日付を文字列に変換するユーティリティです。同時アクセス下で不具合になりうる行を選んでください。",
    code: [
      "public class DateUtil {",
      "    private static final Logger log = LoggerFactory.getLogger(DateUtil.class);",
      "    private static final SimpleDateFormat FORMAT =",
      "        new SimpleDateFormat(\"yyyy-MM-dd\");",
      "",
      "    public static String format(Date date) {",
      "        Objects.requireNonNull(date);",
      "        log.trace(\"Formatting date: {}\", date);",
      "        return FORMAT.format(date);",
      "    }",
      "",
      "    public static Date parse(String text) throws ParseException {",
      "        return FORMAT.parse(text);",
      "    }",
      "}",
    ],
    antiPatternLines: [3, 4, 9, 13],
    patternName: "スレッドセーフでない SimpleDateFormat の共有",
    explanation:
      "SimpleDateFormat はスレッドセーフではありません。static フィールドで共有し、format/parse から呼び出すと複数スレッドで壊れた結果や例外が出ます。DateTimeFormatter（java.time）や ThreadLocal を検討しましょう。",
    hint: "このフォーマッタは複数スレッドから同時に使われます。",
  },
  {
    id: 27,
    difficulty: "advanced",
    title: "ロックの選び方",
    description:
      "ロックの選び方です。他のコードと意図せずロックを共有しうる宣言行を1つ選んでください。",
    code: [
      "public class Worker {",
      "    private static final Logger log = LoggerFactory.getLogger(Worker.class);",
      "    private Boolean lock = Boolean.FALSE;",
      "",
      "    public void critical() {",
      "        log.debug(\"Entering critical section\");",
      "        synchronized (lock) {",
      "            doWork();",
      "        }",
      "        log.debug(\"Exiting critical section\");",
      "    }",
      "",
      "    private void doWork() {",
      "        // business logic",
      "    }",
      "}",
    ],
    antiPatternLines: [3],
    patternName: "ボックス化型への同期",
    explanation:
      "Boolean.FALSE などの共有インスタンスに同期すると、無関係なコードとロックが衝突し得ます。専用の private final Object lock = new Object() を使いましょう。",
    hint: "この lock オブジェクトは JVM 全体で共有され得ます。",
  },
  {
    id: 28,
    difficulty: "advanced",
    title: "リクエストコンテキスト",
    description:
      "リクエストごとにユーザーコンテキストを保持する処理です。ワーカースレッド再利用時に片付けが不十分な行を1つ選んでください。",
    code: [
      "public class RequestContext {",
      "    private static final Logger log = LoggerFactory.getLogger(RequestContext.class);",
      "    private static final ThreadLocal<User> CURRENT = new ThreadLocal<>();",
      "",
      "    public void handle(User user) {",
      "        Objects.requireNonNull(user);",
      "        CURRENT.set(user);",
      "        log.debug(\"Context set for user: {}\", user.getId());",
      "        try {",
      "            process();",
      "        } finally {",
      "            CURRENT.set(null);",
      "        }",
      "    }",
      "",
      "    private void process() {",
      "        User current = CURRENT.get();",
      "        log.trace(\"Processing for user: {}\", current);",
      "    }",
      "}",
    ],
    antiPatternLines: [12],
    patternName: "ThreadLocal の誤った片付け",
    explanation:
      "ThreadLocal は set(null) ではなく remove() で片付ける必要があります。set(null) でもエントリが残り、スレッドプール再利用時にメモリリークや情報漏洩の原因になります。",
    hint: "null を入れることと、ThreadLocal 自体を外すことは同じですか？",
  },
  {
    id: 29,
    difficulty: "advanced",
    title: "リソース解放のタイミング",
    description:
      "ネイティブリソース解放の実装です。現代の Java で推奨されない手法を使っている行を1つ選んでください。",
    code: [
      "public class NativeBuffer implements AutoCloseable {",
      "    private static final Logger log = LoggerFactory.getLogger(NativeBuffer.class);",
      "    private long peer;",
      "    private boolean closed;",
      "",
      "    public NativeBuffer(long size) {",
      "        this.peer = allocate(size);",
      "        log.debug(\"Allocated native buffer: {}\", peer);",
      "    }",
      "",
      "    @Override",
      "    protected void finalize() {",
      "        free(peer);",
      "    }",
      "",
      "    @Override",
      "    public void close() {",
      "        if (!closed) {",
      "            free(peer);",
      "            closed = true;",
      "        }",
      "    }",
      "",
      "    private static native long allocate(long size);",
      "    private static native void free(long peer);",
      "}",
    ],
    antiPatternLines: [12],
    patternName: "finalize によるリソース解放",
    explanation:
      "finalize は呼び出しタイミングが不定で、Java 9 以降非推奨です。リソース解放に頼るべきではありません。AutoCloseable と try-with-resources、または Cleaner を使いましょう。",
    hint: "ガベージコレクションに頼る解放はいつ走りますか？",
  },
  {
    id: 30,
    difficulty: "advanced",
    title: "ロックの公開範囲",
    description:
      "同期に使うロックの定義です。外部から介入されうる設計になっている行を1つ選んでください。",
    code: [
      "public class Counter {",
      "    private static final Logger log = LoggerFactory.getLogger(Counter.class);",
      "    public final Object lock = new Object();",
      "    private int value;",
      "",
      "    public int getValue() {",
      "        return value;",
      "    }",
      "",
      "    public void increment() {",
      "        synchronized (lock) {",
      "            value++;",
      "            log.trace(\"Incremented to {}\", value);",
      "        }",
      "    }",
      "}",
    ],
    antiPatternLines: [3],
    patternName: "公開されたロックオブジェクト",
    explanation:
      "lock が public だと、外部コードが同じオブジェクトで synchronized でき、デッドロックや予期しないブロッキングの原因になります。private final にしましょう。",
    hint: "誰でもこのロックを取得できてしまいます。",
  },
  ...moreQuestions,
];

if (typeof import.meta.env !== "undefined" && import.meta.env.DEV) {
  void import("./validateQuestions").then(({ assertQuestionsValid }) => {
    assertQuestionsValid(questions);
  });
}

export function getQuestionsByDifficulty(difficulty: Difficulty): QuizQuestion[] {
  return questions.filter((q) => q.difficulty === difficulty);
}

export function countByDifficulty(difficulty: Difficulty): number {
  return getQuestionsByDifficulty(difficulty).length;
}

export function shuffleQuestions<T>(array: T[]): T[] {
  const copy = [...array];
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy;
}
